### ISSUE TITLE
Can't access Traefik dashboard on a QNAP NAS (lan network)

### ISSUE THREAD

**Issue by mooglestiltzkin** [Heziode/traefik-v2-https-ssl-localhost#5]
Not sure it's working for me :{

logs says
```

27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Traefik version 2.9.6 built on 2022-12-07T14:17:58Z"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://doc.traefik.io/traefik/contributing/data-collection/\n"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Starting provider aggregator aggregator.ProviderAggregator"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Starting provider *file.Provider"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=error msg="Cannot start the provider *file.Provider: yaml: unmarshal errors:\n  line 20: mapping key \"http\" already defined at line 1"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Starting provider *traefik.Provider"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Starting provider *docker.Provider"
27/12/2022 7:14:17
time="2022-12-26T23:14:17Z" level=info msg="Starting provider *acme.ChallengeTLSALPN"

```

so line 20 in docker compose was
```

version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    
    
    
    ports:
      # Web
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - /share/Container/traefik/config/static.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - /share/Container/traefik/config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - /share/Container/traefik/config/certs:/etc/certs:ro
      
  
      
      
    networks:
      - proxy

networks:
  proxy:
    external: true


```
the traefik.yml line.

not sure how to fix this.

for http://server ip there is a 404 response. But when i do /dashboard/ nothing happens.  even the traefik.docker.localhost](https://traefik.docker.localhost/   doesnt seem to work at all

**Comment by Heziode** [comment]
Hi @mooglestiltzkin, what operating system do you use?

**Comment by mooglestiltzkin** [comment]
docker on a qnap nas using portainer

**Comment by mooglestiltzkin** [comment]
i consulted with a colleague, he suspects the part you left out was local dns setup on the router side of things. this part no idea what to do. Using a pfsense router :/

One possible solution i found was this, but when i tried it, i couldn't get that to work
https://blog.ianpreston.ca/docker/traefik/networking/tip/2021/01/09/traefik-lan.html#introduction

**Comment by Heziode** [comment]
What is the content of your `static.yml` and `dynamic.yml`

> docker on a qnap nas using portainer

I personally use this config on my own QNAP NAS at home without any issues.

Do you plan to access your services from outside of your network?

**Comment by mooglestiltzkin** [comment]
just for local lan for homelab. no remote whatsoever.

my purpose is mostly to familiarize with traefik without exposing ports online in the process. also the fact traefik can handle ports for the many docker apps, so thought that may be a way for handling that in a local setting.

for static and dynamic i pretty much just followed the same as ur file. the only addition i added was a basic auth. but even before that it still didn't work.

```
global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

```

```

http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "domain.local"
            sans:
              - "*.domain.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
      
http:
  middlewares:
    basic-user:
      basicAuth:
        users:
          - "testing:$43v5344g3geww" # generate 
          
```

**Comment by mooglestiltzkin** [comment]
do u have discord?

Unofficial QNAP discord server!
Server Invite: https://discord.gg/Zj9EYsf

**Comment by Heziode** [comment]
# The fix

The problem occur because you have `http` defined twice in the root configuration.

You have to merge them. Here is the working configuration, based on your setup:

```yaml
http:
  middlewares:
    basic-user:
      basicAuth:
        users:
          - "testing:$43v5344g3geww" # generate 
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      middlewares:
        - basic-user
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "domain.local"
            sans:
              - "*.domain.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
```

that's it for this problem 🙂

---

# Additional information for running on Server, NAS / QNAP

Originally, this project is to be used to host and access the services of its own machine (localhost). However, it is possible to do some modification to use this setup on a remote machine (server, nas on local network, etc.).

## General setup

You have to change `docker.localhost` by something like `docker.lan` if you run on lan, or by your own domain name, like `yourdomain.com`.

## Setup with Traefik on a home machine

On your router / ISP box, you have to redirect `docker.lan` or `yourdomain.com` to the machine where Traefik is installed.

You should also probably redirect ports.

## QNAP

For QNAP users, Traefik shall run on different port than 80 & 443, because it is used by several services of QNAP.
So, the `docker-compose.yml` should be something like this:

```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      # Web
      - 8480:80
      - 8443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
```

In the previous example, `8480` and `8443` ports on the QNAP is used respectively for HTTP, and HTTPS.
